name: master
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  font_awesome_flutter:
  dio:
  provider:
  # bloc_pattern:
  # rxdart:
  shared_preferences:
  date_format:
  flutter_dotenv:
  badges:
  flutter_spinkit:
  rflutter_alert:
  cryptoutils:

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  # Sample Import Asset, like this:
  assets:
    - .env
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # Sample Import Font, like this:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
